micronaut:
  application:
    name: catalogue
  server:
    port: -1

mongodb:
  uri: "mongodb://leandro:123@0.0.0.0:27017/catalogue_db"
  cluster:
    maxWaitQueueSize: 5
    connectionPool:
      maxSize: 20
consul:
  client:
    defaultZone: "${CONSUL_HOST:localhost}:${CONSUL_PORT:8500}"
endpoints:
  health:
    enabled: true
catalogue:
  api:
    version: v1