micronaut:
  application:
    name: recommendations
  server:
    port: -1
redis:
  uri: "redis://${REDIS_HOST:localhost}:${REDIS_PORT:6379}"

consul:
  client:
    defaultZone: "${CONSUL_HOST:localhost}:${CONSUL_PORT:8500}"
endpoints:
  health:
    enabled: true
catalogue:
  api:
    version: v1