openapi: 3.0.1
info:
  title: Catalogue
  description: Catalogue API
  contact:
    name: Leandro
    url: https://www.linkedin.com/in/leandroca/
    email: leandro.ueg@gmail.com
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0
  version: v1.0
tags:
- name: Conference
- name: Route
paths:
  /${catalogue.api.version}/catalogue:
    get:
      operationId: list
      parameters: []
      responses:
        default:
          description: list default response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Single_List_CatalogueEntity__'
    post:
      operationId: save
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CatalogueEntity'
        required: true
      responses:
        default:
          description: save default response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Single_CatalogueEntity_'
  /${catalogue.api.version}/catalogue/vendor/{vendor}:
    get:
      operationId: byVendor
      parameters:
      - name: vendor
        in: path
        required: true
        schema:
          type: string
      responses:
        default:
          description: byVendor default response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Single_List_CatalogueEntity__'
  /${catalogue.api.version}/catalogue/title/{title}:
    get:
      operationId: findByTitle
      parameters:
      - name: title
        in: path
        required: true
        schema:
          type: string
      responses:
        default:
          description: findByTitle default response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Single_List_CatalogueEntity__'
components:
  schemas:
    Single_List_CatalogueEntity__:
      type: object
    Single_CatalogueEntity_:
      type: object
    Product:
      required:
      - title
      type: object
      properties:
        product-id:
          type: string
          format: uuid
        title:
          minLength: 1
          type: string
        description:
          type: string
        vendor:
          type: string
        type:
          $ref: '#/components/schemas/ProductType'
    ProductType:
      type: string
      enum:
      - FOOD
      - AUTOMOBILE
      - FURNITURE
      - UNDEFINED
    CatalogueEntity:
      type: object
      allOf:
      - $ref: '#/components/schemas/Product'
